//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class experts
    {
        public experts()
        {
            this.commissionorders = new HashSet<commissionorders>();
            this.documents = new HashSet<documents>();
            this.legalissues = new HashSet<legalissues>();
        }
    
        public int idExperts { get; set; }
        public string name { get; set; }
        public string workplace { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string idDocument { get; set; }
        public Nullable<int> idCommissionOrder { get; set; }
        public Nullable<int> idLegalIssue { get; set; }
    
        [JsonIgnore]
        public virtual ICollection<commissionorders> commissionorders { get; set; }
        [JsonIgnore]
        public virtual ICollection<documents> documents { get; set; }
        [JsonIgnore]
        public virtual ICollection<legalissues> legalissues { get; set; }
    }
}
