//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class registerEntities : DbContext
    {
        public registerEntities()
            : base("name=registerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<commissionorders> commissionorders { get; set; }
        public virtual DbSet<documents> documents { get; set; }
        public virtual DbSet<expertise_type> expertise_type { get; set; }
        public virtual DbSet<experts> experts { get; set; }
        public virtual DbSet<legalissues> legalissues { get; set; }
        public virtual DbSet<qualifications> qualifications { get; set; }
    }
}
