//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qualifications
    {
        public int idQualifications { get; set; }
        public int CommissionOrders_idCommissionOrders { get; set; }
        public int Expertise_type_idExpertise_type { get; set; }
    
        public virtual commissionorders commissionorders { get; set; }
        public virtual expertise_type expertise_type { get; set; }
    }
}
